[common_deps]
lib_deps =
    https://github.com/adafruit/Adafruit-GFX-Library
    ; https://github.com/Bodmer/TJpg_Decoder.git
    ESP32Ping

[common_flags]
build_flags =
    -I include
    -I include/apps
    -I include/coresys
    -I include/drivers
    -I include/kernel
    -I include/apps/misc
    -I include/apps/games
    -I include/apps/tools

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    ${common_deps.lib_deps}

monitor_speed = 115200

build_flags = 
    ${common_flags.build_flags}
    -DCONFIG_ESP_TASK_WDT_TIMEOUT_S=10
    -DDEVICE_ESP32_STANDARD

; 240MHz
board_build.f_cpu = 240000000L

[env:esp32s3dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    ${common_deps.lib_deps}

monitor_speed = 115200

build_flags = 
    ${common_flags.build_flags}
    -DCONFIG_ESP_TASK_WDT_TIMEOUT_S=10
    -DDEVICE_ESP32_S3
    -DSTS_SPI_SPEED=40000000 

; 240MHz
board_build.f_cpu = 240000000L

[env:waveshare_rp2350_pizero]
platform = raspberrypi
board = waveshare_rp2350_pizero
framework = arduino

lib_deps = 
    https://github.com/adafruit/Adafruit-ST7735-Library
    https://github.com/adafruit/Adafruit-GFX-Library
    

build_flags = 
    ${common_flags.build_flags}
    -DDEVICE_RP2350
    -D__FREERTOS=1
    -DSTS_SPI_SPEED=40000000 
    -fexceptions
